In [1]:
import pandas as pd
x=pd.read_csv("/content/train.csv")
print(x)
y=x["price_range"]
print("target variables",y)
z=x.drop('price_range',axis=1)
print(z)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

In [2]:
from sklearn.preprocessing import MinMaxScaler
scalar=MinMaxScaler(feature_range=(0,1))
z_norm = scalar.fit_transform(z)
print(z_norm)

[[0.22778891 0.         0.68       ... 0.         0.         1.        ]
 [0.34736139 1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.94188377 0.         0.16       ... 1.         1.         0.        ]
 [0.6753507  0.         0.16       ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]


In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(z_norm,y,test_size=0.2)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[0.53907816 0.         0.56       ... 1.         0.         1.        ]
 [0.1509686  1.         0.4        ... 1.         0.         1.        ]
 [0.69205077 1.         0.8        ... 1.         1.         1.        ]
 ...
 [0.9752839  1.         0.4        ... 1.         1.         1.        ]
 [0.22845691 0.         0.52       ... 1.         0.         1.        ]
 [0.00534402 1.         0.04       ... 1.         0.         0.        ]]
[[0.87641951 1.         0.04       ... 1.         1.         0.        ]
 [0.45223781 0.         0.68       ... 1.         1.         0.        ]
 [0.72211089 0.         0.92       ... 1.         1.         1.        ]
 ...
 [0.12358049 1.         0.         ... 0.         1.         0.        ]
 [0.71075484 1.         0.         ... 1.         1.         1.        ]
 [0.02805611 1.         0.         ... 1.         1.         0.        ]]
197     3
1148    1
142     3
248     1
371     1
       ..
1967    1
616     3
1871    3
618     3
9       0
Na

In [4]:
import pandas as pd
x=pd.read_csv("/content/heart.csv")
print(x)
y=x["target"]
print("target variables",y)
z=x.drop('target',axis=1)
print(z)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [5]:
from sklearn.preprocessing import MinMaxScaler
scalar=MinMaxScaler(feature_range=(0,1))
z_norm = scalar.fit_transform(z)
print(z_norm)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]


In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(z_norm,y,test_size=0.25)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[0.5625     0.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.5625     0.         0.33333333 ... 0.5        0.         0.66666667]
 ...
 [0.3125     1.         0.66666667 ... 1.         0.         0.66666667]
 [0.58333333 0.         0.         ... 0.5        0.         1.        ]
 [0.60416667 1.         0.33333333 ... 0.5        1.         1.        ]]
[[0.29166667 0.         0.         0.35849057 0.49086758 1.
  0.         0.49618321 1.         0.48387097 0.5        0.
  1.        ]
 [0.6875     1.         0.33333333 0.24528302 0.35388128 0.
  0.         0.24427481 0.         0.22580645 0.5        0.25
  1.        ]
 [0.58333333 1.         0.         0.1509434  0.47716895 0.
  0.5        0.54961832 1.         0.48387097 0.5        0.25
  1.        ]
 [0.25       1.         0.33333333 0.1509434  0.24885845 0.
  0.5        0.6259542  0.         0.         1.         0.
  0.66666667]
 [0.4375     1. 

In [19]:
import numpy as np
x1=x_train[:,0]
x2=x_train[:,1]
x3=x_train[:,2]
x4=x_train[:,3]
x5=x_train[:,4]
x6=x_train[:,5]
x7=x_train[:,6]
x8=x_train[:,7]
x9=x_train[:,8]
x10=x_train[:,9]
x11=x_train[:,10]
x12=x_train[:,11]
x13=x_train[:,12]
y_p=[]
def perceptron(w1,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,b):
  for i in range(len(x1)):
    z=x1[i]*w1+x2[i]*w2+x3[i]*w3+x4[i]*w4+x5[i]*w5+x6[i]*w6+x7[i]*w7+x8[i]*w8+x9[i]*w9+x10[i]*w10+x11[i]*w11+x12[i]*w12+x13[i]*w13+b
    s=1/1+np.exp(-z)
    if(s>=0.5):
      y_p.append(1)
    else:
      y_p.append(0)
perceptron(1,1,1,1,1,1,1,1,1,1,1,1,1,1)
b=(y_p)
print(b)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [20]:
print(y_p)
print(len(y_p))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
227


In [21]:
l=[]
import numpy as np
x=np.array(y_train)==np.array(y_p)
print(sum(x)/len(y_p))

0.5374449339207048
